### ISSUE TITLE
Code should be provided inside a Playground

### ISSUE THREAD

**Issue by BalestraPatrick** [hollance/swift-algorithm-club#1]
Hey! 

Great project and idea! I'm a computer science student and I'm sure many developers will find this repo very useful. 
I was thinking that maybe it'd be better to provide the Swift code inside a Playground so people can start running an algorithm and play around with it right away. What do you think? 😀

**Comment by hollance** [comment]
Thanks!

I might provide playgrounds too, but I also want to keep this readable on the web without having to go into Xcode. Unfortunately, playgrounds are hard to read on the web.

But definitely something to add! :-)

**Comment by BalestraPatrick** [comment]
Sure, sounds good to me!
