### ISSUE TITLE
typealias Element in the HashTable section

### ISSUE THREAD

**Issue by joaopaulogalvao** [hollance/swift-algorithm-club#100]
In the HashTable section, while applying it on a new project file, I noticed that `private typealias Element `, with uppercase E, in this part:

```
public struct HashTable<Key: Hashable, Value> {
  private typealias Element = (key: Key, value: Value)
  private typealias Bucket = [Element]

  private var buckets: [Bucket]
  private(set) var count = 0

  public init(capacity: Int) {
    assert(capacity > 0)
    buckets = .init(count: capacity, repeatedValue: [])
  }

  public var isEmpty: Bool {
    return count == 0
  }

 ...

}
```
seems to be the same one used in the `for-loop` in the `updateValue` function here : 

```
public mutating func updateValue(value: Value, forKey key: Key) -> Value? {
  let index = indexForKey(key)

  // Do we already have this key in the bucket?
  for (i, element) in buckets[index].enumerate() {
    if element.key == key {
      let oldValue = element.value
      buckets[index][i].value = value
      return oldValue
    }
  }
       ...
}
```
It works fine on a couple of tests I tried, but is `element` referencing `Element` somehow? I could not get it. If it is a typo I can submit a pull request.

Thanks for this amazing source, it has been helping me a lot with my studies.

**Comment by hollance** [comment]
`Element` is the name of the type. In the for-loop, `element` is a variable that contains an object of type `Element`. So they are two different, but related, things. 

In the for loop you could call it something else, `for (i, e) in buckets[index].enumerate()` and it will still work. So the fact that it's also called "element" is not really that important.

**Comment by joaopaulogalvao** [comment]
That is great, got it.
Thanks a lot for the explanation.
I will go ahead and close this thread.
