### ISSUE TITLE
Xcode version

### ISSUE THREAD

**Issue by armcknight** [hollance/swift-algorithm-club#110]
Any plans to upgrade the Xcode version set in travis?

**Comment by hollance** [comment]
I guess that should be 7.3 now, but there aren't that many differences between 7.2 and 7.3 when it comes to Swift so it's no big deal to leave it at 7.2 either. ;-)

**Comment by armcknight** [comment]
I was not able to compile my code, because I'm using the new `associatedType` keyword in my protocols. Good news is, everything else still seems to work ok!

**Comment by hollance** [comment]
Ah OK, that makes sense. I think that was the only major change between 7.2 and 7.3.
