### ISSUE TITLE
Dependency managers

### ISSUE THREAD

**Issue by armcknight** [hollance/swift-algorithm-club#111]
Are there any plans to make this available through carthage, cocoapods or SPM? This may dictate how we set up our submissions. Some want library/framework targets, others want a file/directory structure (SPM).

**Comment by hollance** [comment]
The primary purpose of this repo is to educate, not to be a library of production quality algorithms that are ready for plugging into apps. So I don't feel there is much value in making it available as a package through a package manager.

**Comment by armcknight** [comment]
I respect your wishes, and am still excited about adding more stuff here. Admittedly I had allusions of contributing to something like the beginnings of the Boost library for Swift ;)

**Comment by hollance** [comment]
There is no reason why you can't set up a SwiftyBoost repo yourself. :-) Or even contribute to the official Swift stdlib now that it is open source. ;-)

**Comment by armcknight** [comment]
That is a good idea as well--serious fame! I hope you don't mind if I shop my submissions around elsewhere. Keep up the good work here!
