### ISSUE TITLE
Let be friends

### ISSUE THREAD

**Issue by EvgenyKarkan** [hollance/swift-algorithm-club#31]
Hi @hollance 
Some times ago I decided to create very similar repo with ObjC code.
https://github.com/EvgenyKarkan/EKAlgorithms
Can we mention each other in our repos? 
It would be great if we could be friends.
I guess it will be useful for community.

Best wishes.

**Comment by hollance** [comment]
I like friends! I'll add your repo as a link to the main readme. :-)

**Comment by EvgenyKarkan** [comment]
Great, thank you. 
I will do the same asap.
