### ISSUE TITLE
Gratuitous plug: production-quality implementations

### ISSUE THREAD

**Issue by lorentey** [hollance/swift-algorithm-club#52]
I have made production-quality Swift implementations of some common algorithms and data structures. 
Some/all of them might be a bit too complex for educational use, but feel free to use them as you like. 
(Or it might be useful to link to them, to illustrate the work necessary to make stuff feature complete, reusable and performant.)

- [Arbitrary precision integers](https://github.com/lorentey/BigInt)
- [Deque](https://github.com/lorentey/Deque) using a circular buffer
- [In-memory B-Trees and ordered collection types](https://github.com/lorentey/BTree) with copy-on-write value semantics
- [Red-Black Trees](https://github.com/lorentey/RedBlackTree) with COW value semantics

Feel free to close this if they're not a good fit!

**Comment by hollance** [comment]
Thanks. I'll definitely take a look at those. :-)

**Comment by hollance** [comment]
Good stuff! I added the link to the "Learn more!" section.
