### ISSUE TITLE
GCD recursive

### ISSUE THREAD

**Issue by Hout** [hollance/swift-algorithm-club#53]
By making the GCD function recursive, there is much more clarity and it justifies the text better than with the while loop:
```
func gcd(m: Int, _ n: Int) -> Int {
    let r = m % n

    if r == 0 {
        return n
    }
    return gcd(n, r)
}
```

**Comment by hollance** [comment]
Personally I prefer iteration over recursion, but I'll add your version to the description. Thanks!

**Comment by Hout** [comment]
What we are discussing is a procedural loop vs recursion not iteration vs recursion. I think indeed that the loop is more efficient with fewer stack operations. IMHO A recursion can express the basics of an algorithm better:
- start condition
- repeating iteration
- stop condition

I will get my HTS books from the attic this week to get it justified by a proper rationale.

**Comment by hollance** [comment]
OK, I've added a recursive version to the description. :-)

**Comment by Hout** [comment]
Looks nice!
