### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by jherna37** [hollance/swift-algorithm-club#54]
Hey!
I'd like to write a guide and provide an example for Bubble Sort. Though I agree we shouldn't have to learn it, I'd like to use the opportunity to familiarize myself with GitHub and continue to contribute this project. 
Thanks

**Comment by hollance** [comment]
Of all the algorithms you could choose... ;-)

I'd prefer it if you'd pick something else, maybe radix sort or something. But if you must do bubble sort, create a pull request for it, and we'll see...
